import Navbar from '@/components/navbar/Navbar';
import { Metadata } from 'next';
import { AppProps } from 'next/app.js';
import { Poppins } from 'next/font/google';
import '../styles/globals.scss';
import { useRouter } from 'next/router.js';

const poppins = Poppins({weight: '400', subsets: ["devanagari"]})

export const metadata: Metadata = {
  title: 'Create Next _app',
  description: 'Generated by create next app',
}


export default function App({Component, pageProps}: AppProps){
  const router = useRouter();

  return (
    <div className={poppins.className}>
      <Navbar/>
      <main style={{marginTop: router.pathname === '' ? 0 : 50 }}>{<Component {...pageProps} />}</main>
    </div>
  )
}